import styles from "./TermsContent.module.css";

const TermsContent = () => {
  return (
    <div className={styles.wrapper}>
      <h1>Terms of Service</h1>
      <p>
        This document is an electronic record in terms of Information Technology
        Act, 2000 including all its amendments and rules made thereunder as
        applicable and the amended provisions pertaining to electronic records
        in various statutes as amended by the Information Technology Act, 2000.
        This electronic record is generated by a computer system and does not
        require any physical or digital signatures
      </p>
      <p>
        These terms may be updated from time to time in the future. You agree to
        review our Terms of Service regularly by visiting this page. Your
        continued access to or use of the service will mean that you agree to
        the changes. You will be notified of any significant changes to our
        Terms of Service.
      </p>
      <hr />
      <h2>VENDOR AGREEMENT</h2>
      <p>
        This Vendor Agreement (hereinafter referred to as “Agreement”) is made
        on the day of your acceptance of this Agreement from your designated
        electronic mail address or in any other form of electronic record
        including, if applicable or provided, clicking on the check box or “I
        Agree” / “Accept” button or by any other means which construe your
        acceptance of this Agreement (“Execution Date”) by and between
      </p>
      <p>
        This Vendor Agreement (hereinafter referred to as “Agreement”) is made
        on the day of your acceptance of this Agreement from your designated
        electronic mail address or in any other form of electronic record
        including, if applicable or provided, clicking on the check box or “I
        Agree” / “Accept” button or by any other means which construe your
        acceptance of this Agreement (“Execution Date”) by and between
      </p>
      <p>
        Vendor and Service Provider shall hereinafter be individually referred
        to as “Party” and collectively as “Parties
      </p>
      <p>
        1. Vendor is inter alia engaged in the business of developing and/or
        manufacturing and/or selling various goods and related services in the
        Territory (“Business”);
      </p>
      <p>
        2. Service Provider is inter alia engaged in the business of providing
        SAAS platform which enable online sellers/Vendors to sell across
        multiple online electronic marketplaces. Service Provider is developing
        and operating e-commerce businesses for independent third party
        retailers and manufacturers and providing for those entities / persons
        Service Provider’s proprietary technology, website design and
        development capabilities, order processing capabilities, customer
        service capabilities, fulfillment capabilities and centralized
        inventory, invoicing and payment management to enable those entities /
        persons to offer e-commerce to their customers and such services include
        Platform Services (as defined hereunder) and Transaction Support
        Services (as defined hereunder) (“Service Provider Business”);
      </p>
      <p>
        3. Vendor has approached Service Provider to avail Service Provider
        Business for the purpose of Vendor’s Business and Service Provider has
        agreed to make available Service Provider Business to Vendor;
      </p>
      <p>
        4. Service Provider has made and is in the process of making substantial
        investment both monetary, knowhow and otherwise to establish its trade
        name among consumers and distributors so as to create a retail image
        connoting a specific manner in which goods and services can be presented
        on and sold through the Platform;
      </p>
      <p>
        5. The Parties wish to enter into this Agreement to document and record
        their mutual understandings and agreements in relation to the terms and
        conditions on which Service Provider shall make available Service
        Provider Business to Vendor and Vendor shall avail Service Provider
        Business;
      </p>
      <p>6. These recitals shall form part of the Agreement.</p>
      <p>
        Now therefore, in consideration of the mutual promises and other
        consideration, the sufficiency of which is acknowledged, the Parties,
        intending to be legally bound, agree as follows:
      </p>

      <h2>1. DEFINITIONS</h2>

      <p>
        <strong>“Affiliate”</strong> shall mean, with respect to each Party, any
        person or entity directly or indirectly through one or more intermediary
        Controlling, Controlled by, or under direct or indirect common Control
        with a Party. “Control”, “Controlled” or “Controlling” shall mean, with
        respect to any person or entity, any circumstance in which such person
        or entity is controlled by another person or entity by virtue of the
        latter person or entity controlling the composition of the board of
        directors or managers or owning the largest or controlling percentage of
        the voting securities of such person/entity or otherwise controlling the
        other.
      </p>
      <p>
        <strong>“Brand”</strong> or <strong>“Brand Name”</strong> shall mean for
        the Service Provider “HEXBIT.IO™” or such other successor or replacement
        brand name / trade mark / service mark as may be decided by the Service
        Provider and for the Vendor any trademark or brand name decided by them
        and intimated to the Service Provider in writing.
      </p>
      <p>
        <strong>“Confidential Information”</strong> means and includes any and
        all information which is confidential to a Party including any (i)
        business information and business processes, (ii) any samples,
        formulations, specifications, data relating to manufacturing and quality
        control processes and procedures, (iii) advertising and marketing plans,
        (iv) any past, current or proposed development projects or plans for
        future development work, (v) technical, marketing, financial and
        commercial information whether relating to past or current or future,
        (vi) the commercial and business affairs of a Party, (vi) all
        customer-related information including any rates and discounts and (vii)
        and with respect to the Service Provider shall include the End Customer
        Database.
      </p>
      <p>
        <strong>“Deliverable(s)”</strong> shall mean the specific materials,
        devices, products, services or other deliverables that are provided by
        Vendor to Service Provider during the course of performing Service
        Provider Business as per this Agreement and any related document
        thereto.
      </p>
      <p>
        <strong>“End Customer”</strong>shall mean the retail customers to whom
        Vendor offers to sell or sells or from whom Vendor receives offers to
        purchase the Products through the Platform.
      </p>
      <p>
        <strong>“End Customer Database”</strong> shall mean all data /
        information (as may be updated from time to time) about the persons/
        entities including their names, addresses, contact details, queries,
        orders and other requests made available by such persons / entities on
        the Platform or otherwise captured by the Platform that shall further
        include the usage, behavior, trends and other statistical information /
        data relating to such persons / entities, who (i) access the Platform or
        otherwise get invitation to the Platform or correspond with the
        Platform, (ii) place any order for Products on the Platform, or (iii)
        send any enquiry/ request with respect to the Platform, and shall
        include all analysis and records based on such aforementioned
        information, including the spending and other patterns of such
        persons/entitles and Products. For the avoidance of doubt, any list,
        description or other grouping of consumers or customers or any
        derivative work from End Customer Database shall be deemed to be End
        Customer Database.
      </p>
      <p>
        <strong>“Intellectual Property”</strong> includes ideas, concepts,
        creations, discoveries, inventions, improvements, know how, trade or
        business secrets; trademarks, service marks, domain names, designs,
        utility models, tools, devices, models, methods, patents, copyright
        (including all copyright in any designs and any moral rights), masks
        rights, design right, procedures, processes, systems, principles,
        algorithms, works of authorship, flowcharts, drawings, books, papers,
        models, sketches, formulas, teaching techniques, electronic codes,
        proprietary techniques, research projects, and other confidential and
        proprietary information, computer programming code, databases, software
        programs, data, documents, instruction manuals, records, memoranda,
        notes, user guides; in either printed or machine-readable form, whether
        or not copyrightable or patentable, or any written or verbal
        instructions or comments. The End Customer Database shall be considered
        to be the Intellectual Property of the Service Provider.
      </p>

      <p>
        <strong>“Intellectual Property Rights”</strong> means and includes (i)
        all rights, title or interest under any statute or under common law or
        under customary usage including in any Intellectual Property or any
        similar right, anywhere in the world, whether negotiable or not and
        whether registerable or not, (ii) any licenses, permissions and grants
        in Intellectual Property (iii) applications for any of the foregoing and
        the right to apply for them in any part of the world and (iv) all
        extensions and renewals thereto.
      </p>

      <p>
        <strong>“Payment Facilitation Services”</strong> shall mean facilitating
        the receipt of Sale Price on the Platform either along with Platform
        Services or otherwise (for example cash on delivery services).
      </p>

      <p>
        <strong>“Platform”</strong> shall mean the website with a second level
        domain name / uniform resource locator (URL) bearing the Brand Name with
        any top level domain name whether presently available for registration
        or made available for registration at any future date.
      </p>

      <p>
        <strong>“Platform Services”</strong> internet based electronic platform
        in the form of an intermediary to facilitate sale and purchase of goods
        and services through Platform.
      </p>

      <p>
        <strong>“Product(s)”</strong> shall mean any and all goods and related
        services of the Vendor for which Service Provider makes available
        Service Provider Business to the Vendor.
      </p>

      <p>
        <strong>“Sale Price”</strong> shall be the price at which the Product is
        offered for sale by the Vendor on the Platform by using Platform
        Services to the End Customer. Parties agree that Sale Price is dynamic
        and volatile and may vary at different times and points of sale and
        therefore can be periodically and from time to time changed or revised
        by the Vendor in accordance with the terms of this Agreement.
      </p>

      <p>
        <strong>“Service Fees”</strong> shall mean the fees for availing either
        whole or part of the Service Provider Business in accordance with the
        terms of this Agreement and/or Commercial Terms (the term as defined in
        the Agreement).
      </p>

      <p>
        <strong>“Service Provider Business”</strong> shall have the meaning as
        set out Recital 2 hereinabove and shall include Platform, Platform
        Services, Payment Facilitation Services and Transaction Support
        Services.
      </p>

      <p>
        <strong>“Service Provider Content”</strong> shall mean the Platform, all
        the pages of the Platform, all the content contained in the Platform
        (excluding any third party content and advertisements), look and feel of
        the Platform, any and all information or content owned or controlled
        (e.g. by license or otherwise) by Service Provider or its Affiliates,
        including text, images, graphics, photographs, video and audio, and
        furnished by Service Provider or its Affiliates in connection with
        Platform Services, Transaction Support Services, Payment Facilitation
        Services and for the purpose of offering for sale of Products by the
        Vendor.
      </p>

      <p>
        <strong>“Term”</strong> shall have the meaning as set out in Section
        13.1 hereto.
      </p>

      <p>
        <strong>“Territory”</strong> shall mean the entire world.
      </p>

      <p>
        <strong>“Transaction Support Services”</strong> shall include services
        in relation to support the sale of the goods and services by the Vendor
        to End Customer which shall include product listings, warehousing
        services, logistics management services, Payment Facilitation Services,
        customer support services and any other additional services that may be
        agreed between the parties.
      </p>

      <h2>2. “Transaction Support Services”</h2>

      <p>In this Agreement, unless the context otherwise requires:</p>
      <p>
        (i) Words importing persons or parties shall include natural person,
        entity, partnership firm, organization, operation, Company, HUF,
        voluntary association, LLP, joint venture, trust, limited organization,
        unlimited organization or any other organization having legal capacity;
      </p>
      <p>
        (ii) Words importing the singular shall include the plural and vice
        versa, where the context so requires;
      </p>
      <p>
        (iii) References to any law shall include such law as from time to time
        enacted, amended, supplemented or re-enacted;
      </p>
      <p>
        (iv) Reference to one gender shall include a reference to the other
        genders;
      </p>
      <p>
        (v) References to the words “include” or “including” shall be construed
        without limitation;
      </p>
      <p>
        (vi) References to this Agreement or any other agreement, deed,
        instrument or document shall be construed as a reference to this
        Agreement, such other agreement, deed, instrument or document as the
        same may from time to time be amended, varied, supplemented or novated
        in accordance with the terms of this Agreement;
      </p>
      <p>
        (vii) The headings and titles in this Agreement are indicative and shall
        not be deemed part thereof or be taken into consideration in the
        interpretation or construction of this Agreement;
      </p>
      <p>
        (viii) The word ‘written’ shall include writing in electronic form and
        ‘signed’ shall include electronic signature or any other electronic
        communication which signifies the sender’s or originator’s intention to
        be bound by such electronic communication.
      </p>

      <h2>3. SERVICES</h2>
      <p>
        3.1 The Vendor appoints the Service Provider and Service Provider
        accepts such appointment to make available the Service Provider Business
        to the Vendor for the Products and in accordance with the terms of this
        Agreement and as further agreed in commercial understanding electronic
        document or any other similar or analogous electronic or other document
        (“Commercial Terms”) and in accordance with various Platform rules and
        policies including privacy policy (“Platform Policies”). The Commercial
        Terms and Platform Policies are deemed to have been incorporated in this
        Agreement by way of reference.
      </p>

      <p>
        3.2 Vendor agrees and acknowledges that Service Provider is free to
        provide Service Provider Business and in the Territory in any manner and
        for any consideration as may be decided by Service Provider in its sole
        and absolute discretion.
      </p>

      <p>
        3.3 Service Provider in its sole and absolute discretion may refuse to
        provide any one or more of the Service Provider Business including
        Platform, Platform Services, Payment Facilitation Services and/or
        Transaction Support Services for any reason whatsoever and especially if
        providing such Service Provider Business to the Vendor can be
        detrimental to the reputation, goodwill and competitiveness of Service
        Provider or could cause any breach of any contractual commitments of the
        Service Provider and cause Service Provider to breach any applicable
        laws.
      </p>

      <p>
        3.4 In the event of any conflict or inconsistency between the terms of
        this Agreement and the terms of any Commercial Terms thereto, the terms
        of this Agreement shall prevail to the extent of such conflict or
        inconsistency.
      </p>

      <h2>4. ADVERTISING, MARKETING AND SALES PROMOTION</h2>

      <p>
        4.1 Service Provider as the proprietor and owner of the Platform and
        Platform Services and rights holder of the Brand Name may at its sole
        discretion carry out advertising and marketing activities in relation to
        promotion of the Platform, Platform Services and Brand Name in any
        manner and to any extent as may be deemed fit by the Service Provider
        and for such purposes may engage in certain sales promotion activities
        to increase the sales of Products on the Platform. The Service Provider
        and Vendor may agree on certain terms on which Vendor shall support such
        sales and marketing activities of Service Provider including providing
        discounts on the Products or other free of cost goods and services to
        the End Customers.
      </p>

      <p>
        4.2 Service Provider may at its sole and absolute discretion on
        reasonable commercial efforts basis market, promote or advertise the
        Products made available for sale by Vendor on the Platform in compliance
        with this Agreement.
      </p>

      <p>
        4.3 Where Vendor believes or is notified by other entity including any
        third party manufacturers of the Products that any promotion plan/
        activity undertaken by Service Provider is against any applicable law or
        in breach of any contractual obligation of Vendor or such third party
        manufacturer (in both cases supported by a written legal opinion from a
        reputed advocate), Vendor shall intimate the same to Service Provider
        and upon such intimation, Service Provider shall within reasonable time
        cease such plan/ activities.
      </p>

      <p>
        4.4 Vendor agrees and acknowledges that Service Provider shall have the
        sole right (as to between Service Provider and Vendor) for the design,
        look and feel, architecture, layout, positioning and all aspects of the
        Platform including listing, positioning, indexing, placement and tiering
        the Products offered for sale on the Platform by the Vendor and the
        Vendor shall not question or dispute such exercise of right or discharge
        of responsibility by the Service Provider.
      </p>

      <p>
        4.5 Service Provider shall be solely responsible at Service Provider’s
        sole discretion to sell or license any and all advertising and
        promotional time and space with respect to Platform including web-pages
        or such portions of the Platform that contains the details of the
        Products. The advertisement and promotions on any part of the Platform
        may include video advertising, display/banner/text advertisements,
        including but not limited to medium rectangle, leaderboard, roadblock,
        hyperlink, page branding, framing, widgets, pop- ups, pop-under, network
        advertisements (for the sake of example, Google AdSense) available on
        the Platform. Service Provider shall have the sole right and discretion
        to decide the style, placement and format of the advertisement and
        promotion and the price and/or any other consideration, if any, for the
        sale and license of such advertisement and promotion. Except for the
        facilitation of payment of sale consideration of the Product through
        Payment Facilitation Services, Service Provider and/or its Affiliates
        shall be entitled to retain any and all revenues generated from any
        sales or licenses of all such advertisements and promotions.
      </p>

      <p>
        4.6 Service Provider shall reasonably ensure that all advertisement/
        promotion activities undertaken by the Service Provider:{" "}
        <p>
          (i) do not contain any material that, in its knowledge, would infringe
          or violate any intellectual property rights or any other personal or
          proprietary right of any person;
        </p>{" "}
        and <p>(ii) are not obscene or libelous; and</p>{" "}
        <p>
          (iii) comply with all applicable laws including standards and rules
          set forth by the Advertising Standards Council of India or any other
          relevant government authority.
        </p>
      </p>
      <h2>5. END CUSTOMER DATABASE</h2>

      <p>
        5.1 The End Customer Database shall be proprietary to the Service
        Provider. Service Provider shall alone retain all rights including all
        Intellectual Property Rights in the End Customer Database and unless
        specifically agreed to in writing by the Service Provider, no rights in
        or to the End Customer Database are deemed to have been granted to the
        Vendor. To the extent Vendor derives any rights in the End Customer
        Database by virtue of it undertaking the Vendor Business the Vendor
        shall hold such rights in trust for Service Provider and the Vendor
        shall do and undertake all such acts to exclusively assign such rights
        in the End Customer Database to the Service Provider. The Vendor further
        agrees that (a) all the End Customer Database shall be treated as
        Confidential Information of the Service Provider for the purposes of
        this Agreement; (b) Service Provider being the owner and proprietor of
        the End Customer Database shall be entitled to use, store and exploit
        the same in any manner as may be deem fit by the Service Provider and in
        accordance with Service Provider’s privacy policy as provided on the
        Platform from time to time; and (c) Vendor shall not use the End
        Customer Database other than selling the Products by availing Service
        Provider Business or required for law enforcement purposes and shall in
        no way sell, transfer or otherwise exploit the End Customer Database
        without the express written consent of the Service Provider.
      </p>

      <h2>6. CONSIDERATION AND PAYMENT TERMS</h2>
      <strong>
        <i>6.1 CONSIDERATION AND PAYMENT TERMS</i>
      </strong>

      <p>
        6.1.1 In consideration of the provision of Service Provider Business by
        the Service Provider, the Vendor shall pay to the Service Provider
        Service Fees which shall be calculated in the manner as specified in the
        Commercial Terms.
      </p>
      <p>
        6.1.2 Service Fees for any additional services shall be as set out in
        the Commercial Terms.
      </p>
      <p>
        6.1.3 Parties agree that the details of terms memorialized by the
        Commercial Terms are dynamic in nature and will evolve or vary as the
        operating, promotional, marketing and business environment of the
        Service Provider or user behavior on the Platform changes and evolves
        and therefore the Commercial Terms will be adjusted or revised from time
        to time or sometime occasionally or frequently by the Parties as
        necessary or appropriate during the Term of the Agreement to accurately
        reflect the evolution of the aforesaid environment and conditions. Such
        revisions would be with the mutual consent of the Parties which consent
        can be oral, written or implied. For any oral consent, Service Provider
        may on reasonable basis confirm such oral consent within reasonable time
        from such consent and through written records including through
        electronic communications.
      </p>

      <strong>
        <i>6.2 Payment Terms:</i>
      </strong>

      <p>
        6.2.1 In consideration of the Services provided by the Service Provider,
        the Service Provider will deduct its commission/service fee from the
        Vendor and remit the cost to the Vendor as per the Commercial Terms
        annexed herewith as Annexure-1.
      </p>
      <strong>
        <i>6.3 Taxes:</i>
      </strong>

      <p>
        Each Party shall be responsible for any and all taxes on its business,
        and taxes based on its net income or gross receipts. However, Service
        Provider shall be entitled to additionally charge service tax or any
        other indirect or transaction taxes as applicable on one or more of the
        Service Provider Business and Service Fees.
      </p>

      <h2>7. ADDITIONAL OBLIGATIONS OF SERVICE PROVIDER</h2>

      <p>
        7.1 Service Provider shall reasonably maintain the Platform and Platform
        Services and shall on reasonable efforts basis provide Transaction
        Support Services and other services comprising Service Provider
        Business.
      </p>

      <p>
        7.2 Service Provider shall reasonably maintain the registration of
        domain name in relation to the Platform during the Term at its own costs
        free from any and all encumbrances, including encumbrances which may
        lead to any adverse effect on Service Provider’s registration of the
        domain name or its use of the Platform.
      </p>

      <p>
        7.3 Service Provider shall ensure that it has or procures adequate
        technology as necessary to maintain the Platform and perform the Service
        Provider Business under this Agreement.
      </p>

      <p>
        7.4 Service Provider, as a part of Transaction Support Services, shall
        list the Products on the Platform for the Vendor at the Sale Price
        provided or informed by the Vendor. Service Provider acknowledges that
        the Sale Price is dynamic and volatile and may vary at different times
        and points of sale and that both Service Provider and the Vendor
        reserves the right to change or modify the Sale Price of the Product at
        any time before the same is bought by the End Customer on the Platform.
        The intimation of such revisions of the Sale Price will be in writing.{" "}
      </p>

      <h2>8. OBLIGATIONS, COVENANTS AND WARRANTIES OF VENDOR</h2>

      <p>
        8.1 Vendor shall not use the Service Provider Business for any purpose
        other than Vendor’s Business and in relation to the Products.
      </p>

      <p>
        8.2 Vendor shall manage and maintain sufficient inventory of the
        Products which the Vendor offers to sell to End Customer on the Platform
        through Platform Services and shall mandatorily deliver the Products as
        purchased by the End Customer to the Service Provider within such time
        as may be prescribed in the Commercial Terms.
      </p>

      <p>
        8.3 Vendor shall deliver exactly the same Product to the Service
        Provider for availing Transaction Support Services from Service Provider
        in relation to the sale of Products to End Customer.
      </p>

      <p>
        8.4 Vendor shall offer the Products for sale on the Platform on the Sale
        Price which shall be inclusive of all taxes, duties, levies, and all
        other charges other than any entry taxes / octroi as applicable in the
        city or municipal limits of the End Customer. The charges pertaining to
        warehousing, packaging, shipping and logistics are subject to mutual
        agreed terms of both the parties. The Sale Price shall be in compliance
        with all applicable laws and shall not be more than the maximum retail
        price printed on the Products.
      </p>

      <p>
        8.5 Vendor shall undertake all the necessary after sales services to the
        End Customer including providing warranty/ guarantee / replacement
        services to the Products.
      </p>

      <p>
        8.6 Customer return has to be accepted immediately by the vendor, the
        vendor has to provide the customer return window post successful
        delivery of goods and if incase the customer returns the product in the
        agreed upon window the vendor has to take back the goods, also the
        charges for reverse logistics has to be borne by the vendor
      </p>

      <p>
        8.7 The vendor shall provide necessary access to the Service Provider to
        inspect the warehouse, manufacturing facilities or other facilities and
        offices of the Vendor in order to ensure Vendor is able to comply with
        its sales obligations to the End Customer. Vendor acknowledges and
        agrees that this ingress, regress and inspection rights of the Service
        Provider is to ensure the goodwill of the Platform, Platform Services
        and Brand Name and to provide good user experience to the End Customer.
      </p>

      <p>
        8.8 Vendor shall ensure that Vendor employs sufficient staff to meet and
        fulfill the requirements of this Agreement and to sell, deliver and
        service the Products sold to the End Customers through Platform
        Services. Vendor shall further ensure that the Vendor’s staff shall
        participate in the relevant training programs as organized or approved
        by the Service Provider from time to time.
      </p>

      <p>
        8.9 Vendor shall not print, emboss or otherwise display any brand name,
        trade name, and trademark, service mark on the Product, on the packing
        material and on the invoice other than those displayed while making the
        sale offer on the Platform while packing the products for delivery to
        Service Provider to avail Transactional Support Services.
      </p>

      <p>
        8.10 Vendor shall provide series of invoice numbers in relation to the
        Products sold to the End Customer(s) through Platform Services and such
        invoice number shall correspond to the books of accounts of the Vendor
        as maintained by the Vendor under applicable law. As a part of availing
        Transaction Support Services, the Vendor hereby authorizes Service
        Provider and Service Provider Affiliates to issue the invoices
        containing invoice number from the aforesaid series to the End Customer
        on behalf of the Vendor for the sale of Products. The Vendor further
        authorizes Service Provider and Service Provider Affiliates to include
        the Brand Name on the invoice and for the avoidance of doubt, the
        inclusion of the Brand Name shall not create any relationship of agency,
        representative, partnership, joint-venture or otherwise between the
        Vendor and Service Provider and the relationship shall always remain as
        that of an independent contractor. Vendor acknowledges and agrees that
        Service Provider shall provide in the invoice all the necessary details
        of the taxes, duties and other statutory levies applicable on the sale
        and delivery of the Product(s) to the End Customer and it shall be the
        duty and obligation of the Vendor to correctly and timely pay or deposit
        such taxes etc. to the appropriate government and shall indemnify,
        defend and hold harmless Service Provider, Service Provider Affiliates
        and their respective shareholders, directors, officers, employees,
        contractors and agents in the event Vendor defaults in making the
        payment of such taxes etc.
      </p>

      <p>
        8.11 The Products offered to be sold by the Vendor on the Platform and
        subsequent delivery of the same to the Service Provider and Deliverables
        shall (a) exactly conform to the specifications and representations made
        by the Vendor on the Platform; (b) shall comply with all the applicable
        laws including that of the territory of the Vendor, the place from where
        Vendor dispatches the Products to the Service Provider and the place of
        final delivery to the End Customer; (c) not infringe any third party’s
        Intellectual Property Rights whether in India or anywhere in the world;
        and (d) not violate any international trade, import and export related
        laws including parallel imports.
      </p>

      <p>
        8.12 Vendor agrees and acknowledges that the title in the Products shall
        only be transferred from Vendor to the End Customer upon delivery of the
        Products to the End Customer. For the avoidance of doubt, the title and
        risk on the Products for any delivery of Products to Service Provider
        for providing any Transaction Support Services before the purchase of
        Products by the End Customer on the Platform shall always remain with
        the Vendor. The Vendor may in its sole discretion take appropriate
        insurances to safeguard itself from any loss, breakage, theft or damage
        of the Products till such time the Products are actually delivered to
        the Customer. The Vendor shall be the lawful owner or the lawful right
        holder in the Products offered and/or sold on the Platform to the End
        Customer and the Products at time of listing of the same on the Platform
        and for all times thereafter shall be free from any encumbrance, charge,
        lien or any security or third party interests. Vendor hereby irrevocably
        and unconditionally waives all its liens whether contractual, statutory,
        equitable or otherwise including those related to unpaid seller on the
        Products once the Products have been delivered by Vendor to either
        Service Provider or to the End Customer or to any carrier or bailee.
      </p>

      <p>
        8.13 The vendor shall pass on the full warranty or guarantee received on
        the Products from the third party manufacturers or third party suppliers
        to the End Customer and shall fully support the End Customer to enforce
        such warranty or guarantee.
      </p>

      <p>
        8.14 The Vendor shall at no point represent or hold itself out as an
        agent or representative or an Affiliate of the Service Provider. The
        sale and purchase transaction between Vendor and the End Customer shall
        be a bi partite contract between them and Service Provider is merely
        facilitating the transaction between Vendor and End Customer as an
        intermediary and a conduit by making available Service Provider Business
        and Payment Facilitation Services to Vendor and End Customer.
      </p>

      <p>
        8.15 The vendor shall provide such necessary assistance (at no
        additional direct cost to Service Provider) as may be required to
        facilitate Service Provider to carry out its obligations under this
        Agreement.
      </p>

      <p>
        8.16 The Vendor shall not make any representation or do any act which
        may be taken to indicate that it has any right, title or interest in or
        to the Brand Name.
      </p>

      <p>
        8.17 Parties agree that they shall not do, cause or authorize to be done
        anything which will or may: (i) impair, damage or be detrimental to the
        rights, reputation and goodwill associated with the other Party, its
        Affiliates, shareholders or directors and/or the Brand Name; (ii) bring
        the other Party’s Brand Name or the Platform into disrepute or any claim
        by third parties; or (iii) may jeopardize or invalidate the other
        Party’s Brand Name;
      </p>

      <p>
        8.18 Neither Party shall use or register anywhere in the world, the
        other Party’s Brand Name or any other trade mark, trade name or domain
        name, except as authorized under this Agreement, which, in the other
        Party’s reasonable opinion, is identical, improvement over, dilution of,
        combination involving or confusingly similar to, the such Party’s Brand
        Name or, that constitutes any translation thereof into any language.
      </p>

      <p>
        8.19 Both Parties understand and acknowledges that other Party’s Brand
        Name and reputation is of utmost importance for other Party’s business
        and that the conduct of other Party in the performance of this Agreement
        and otherwise would have material impact and bearing on such Party’s
        Brand Name and reputation. Further both Parties understand and
        acknowledges that the obligations and covenants placed on the other
        Party in this Section or elsewhere in the Agreement are essential for
        the maintenance of quality control and protection of other Party’s Brand
        Name, and to ensure timely payments to Vendor.{" "}
      </p>

      <h2>9. INTELLECTUAL PROPERTY</h2>
      <h3>9.1 Intellectual Property Rights In Relation To Brand Name</h3>
      <p>
        9.1.1 As between Service Provider and Vendor, Vendor own all right,
        title, and interest in and to Vendor’s Intellectual Property. Service
        Provider obtains no rights under this Agreement from Vendor to Vendor’s
        Intellectual Property.
      </p>
      <p>
        9.1.2 Vendor acknowledges Service Provider’s absolute ownership of,
        interest in and rights to the Brand Name and the Platform.
      </p>

      <p>
        9.1.3 Without limitation to the foregoing, Vendor acknowledges and
        agrees that all goodwill in or associated with the Brand Name, including
        any goodwill generated or arising by or through Service Provider’s or
        Vendor’s activities pursuant to this Agreement shall accrue for the
        benefit of and shall belong exclusively to the Service Provider.
      </p>
      <p>
        9.1.4 No right or interest in the Brand Name are granted or deemed to be
        granted by the Service Provider to the Vendor.
      </p>
      <p>
        9.1.5 References. You grant to Service Provider a non-exclusive,
        worldwide, royalty-free right and license to use your company name and
        logos to identify you as a vendor. This license will survive after the
        term of this Agreement, provided you may terminate this license at any
        time after termination of this Addendum by giving Service Provider at
        least 30 days’ written notice.
      </p>

      <h3>
        9.2 Intellectual Property Rights In Relation To Service Provider Content
        and Service Provider Business
      </h3>

      <p>
        Service Provider shall retain sole ownership of all the intellectual
        properties, know how or other proprietary rights in the Service Provider
        Content and Service Provider Business and no right or interest is
        granted or shall be deemed to be granted by Service Provider to the
        Vendor. To the extent Service Provider Content contains any proprietary
        content or information of the Vendor, the Vendor hereby grants a
        royalty- free and world-wide license to such content or information
        including a right to creative derivative product of such content or
        information.
      </p>

      <h2>10. CONFIDENTIALITY</h2>

      <p>
        10.1 Each Party may disclose to the other such Confidential Information
        as may be necessary to further the performance of this Agreement.
      </p>
      <p>10.2 The receiving Party undertakes to the disclosing Party:</p>

      <p>
        (i) to keep confidential the disclosing Party’s Confidential
        Information;
      </p>
      <p>
        (ii) not to disclose the Confidential Information in whole or in part to
        any other person without the disclosing Party’s prior written consent,
        except to the receiving Party’s employees, agents and sub- contractors
        involved in the performance of this Agreement on a confidential and need
        to know basis and provided that employees, agents and sub-contractors
        are bound by written agreements of confidentiality which are at least as
        stringent as the provisions of this Agreement; and
      </p>
      <p>
        (iii) to use the Confidential Information solely in connection with the
        performance of this Agreement.
      </p>

      <p>
        10.3 The aforementioned confidentiality obligations shall not extend to
        Confidential Information which:
      </p>

      <p>
        (i) has ceased to be confidential without default on the part of the
        receiving Party;
      </p>
      <p>
        (ii) has been received from a third party who did not receive it in
        confidence;
      </p>
      <p>
        (iii) the receiving Party is required by any court, government or other
        regulatory body to disclose, but only to the extent required by law,
        provided that the receiving Party gives the disclosing Party written
        notice as soon as practicable of such requirement and consult in good
        faith the disclosing party on the content and manner of any disclosure.
      </p>

      <p>
        10.4 Upon request by the disclosing Party, the receiving Party must
        deliver to the disclosing Party all documents and other materials in any
        medium in its possession or control which contain or refer to the
        disclosing Party’s Confidential Information. If the documents or other
        materials are not capable of being returned, the receiving Party must
        destroy and certify the destruction of such documents and materials to
        the reasonable satisfaction of the Disclosing Party.
      </p>

      <p>
        10.5 Your and Vendor personal / sensitive personal data / information
        shall be governed by the Privacy Policy of the Platform, which terms
        (including all amendments, modifications, reinstatements and
        substitutions) shall be deemed to be incorporated herein by way of
        reference.
      </p>

      <h2>11. INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>

      <p>
        11.1 The Vendor shall promptly on demand indemnify, defend and hold
        harmless the Service Provider, its Affiliates and End Customer and their
        respective officers, directors, proprietors, partners, managers,
        members, trustees, shareholders, employees and agents (“Indemnified
        Parties”) for and against all claims, liabilities, costs and expenses
        (including reasonable attorney’s fees) incurred or to be incurred by the
        Indemnified Parties that arise out of, in any way relate to, or result
        from any breach by the Vendor of any of the provisions of this
        Agreement, or breach of any laws by the Vendor, or negligence, fraud or
        willful misconduct of the Vendor or its Affiliates and their respective
        officers, directors, shareholders, employees, contractors,
        sub-contractors, agents and personnel. For the avoidance of doubt, it is
        further clarified that the right to indemnification in connection with
        any of the aforesaid claims of cause of action is independent and in
        addition to other rights and remedies of the Indemnified Person that may
        be available at law or in equity. Service Provider shall have a lien on
        the Products and on the consideration received from the End Customer for
        the sale of Products on the Platform until Vendor has fully discharged
        its obligations and liabilities to Indemnified Parties in accordance
        with this Agreement. In the event Vendor is unable to indemnify the
        Indemnified Parties within a reasonable period of time, Service Provider
        shall be entitled to sell or otherwise dispose of the Products and set
        off the proceeds out of such sale and disposing off against Indemnified
        Parties’ indemnification claims and/or if permitted under law or by
        virtue of any order of any court of law Service Provider shall be
        entitled to receive the sale consideration from the payment gateway
        which otherwise would have remitted by such payment gateway to the
        Vendor and/or set off the amounts received by Service Provider from the
        End Customer who has availed cash on delivery services.
      </p>

      <h3>11.2 Service Provider’s Limitation of Liability:</h3>

      <p>
        NOTWITHSTANDING ANYTHING CONTRARY CONTAINIED IN THIS AGREEMENT, IN ANY
        EVENT SERVICE POVIDER AND ITS AFFILIATES SHALL NOT BE LIABLE (WHETHER IN
        CONTRACT, WARRANTY, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE),
        PRODUCT LIABILITY OR OTHER THEORY), TO THE VENDOR OR ANY OTHER PERSON OR
        ENTITY FOR COST OF COVER OR FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES (INCLUDING DAMAGES FOR LOSS
        OF REVENUES, LOSS PROFIT OR ANTICIPATED PROFITS, LOSS OF GOODWILL, LOSS
        OF BUSINESS OR DATA) ARISING OUT OF OR IN RELATION THIS AGREEMENT.
        Service Provider’s entire liability to Vendor under this Agreement or
        under any applicable law or equity shall be limited solely to actual and
        proven direct damages sustained by the Vendor as a result of the gross
        negligence or wilful misconduct of the Service Provider and its
        Affiliate and their respective directors, officers, employees and agents
        in the performance of their respective services and other obligations
        under this Agreement. In no event shall the Service Provider be liable,
        vicariously or otherwise, to the Vendor and its Affiliates or any third
        party for any losses, damages, liabilities, costs (including reasonable
        legal costs) and expenses (including taxation) which are in the
        aggregate in excess of the (i) amounts paid by the Vendor to the Service
        Provider in the immediately preceding twelve month period under this
        Agreement – if such losses et al are due to Platform Services, or (ii)
        the cost of the Products (excluding Services Fees) sold by the Vendor to
        End Customer – if such losses et al are due to Transaction Support
        Services.
      </p>

      <h2>12. FURTHER REPRESENTATIONS AND WARRANTIES</h2>

      <p>
        12.1 In addition to other representations and warranties in this
        Agreement, each Party represents and warrants as follows:
      </p>

      <p>
        (i) it is a corporation duly organized, validly existing, and in good
        standing under the laws of its incorporation;
      </p>

      <p>
        (ii) execution and performance of this Agreement by such Party and the
        consummation of the transactions contemplated hereby do not and will not
        contravene the certificate of incorporation or by-laws of such Party and
        do not and will not conflict with or result in (a) a breach of or
        default under any indenture, agreement, judgment, decree, order or
        ruling to which such Party is a party that would materially adversely
        affect such Party’s ability to perform its obligations under this
        Agreement; or (b) a breach of any applicable law; and
      </p>

      <p>
        (iii) it shall comply with all applicable laws in the performance of its
        obligations and the exercise of its rights under this Agreement.
      </p>

      <p>
        12.2 EXCEPT AS SPECIFIED IN THIS AGREEMENT, NEITHER PARTY MAKES ANY
        WARRANTY IN CONNECTION WITH THE SUBJECT MATTER OF THIS AGREEMENT. EACH
        PARTY HEREBY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES, INCLUDING WITHOUT
        LIMITATION ALL IMPLIED WARRANTIES OF VENDORABILITY, FITNESS FOR A
        PARTICULAR PURPOSE.
      </p>

      <p>
        12.3 Service Provider specifically disclaims any and all express or
        implied warranties with respect to the Platform, Platform Services and
        Payment Facilitation Services and these are provided on ‘as is’ basis.
      </p>

      <h2>13. TERM OF AGREEMENT</h2>

      <p>
        13.1 This Agreement shall commence on the Effective Date and shall be
        valid until termination. (“Term”).
      </p>
      <p>
        13.2 Either party shall have the right to terminate this Agreement and
        all then existing Commercial Terms by issuing a 30-day prior notice of
        termination in writing without any additional obligations or liabilities
        to each other.
      </p>

      <p>
        13.3 Either party shall have a right to terminate this Agreement or any
        Commercial Terms thereto upon any material breach of this Agreement by
        the other Party provided that where in the reasonable opinion of the
        non- breaching Party, such breach is capable of cure, the non-breaching
        Party shall not terminate this Agreement / any Commercial Terms thereto
        without providing the breaching Party a cure period of [thirty (30)
        days] to cure such breach and provide the non-breaching Party with
        necessary documents satisfactorily evidencing cure of such breach.
      </p>

      <p>
        13.4 Service Provider shall have the right to terminate this Agreement
        upon occurrence of any insolvency event in relation to Vendor. It is
        clarified that an insolvency event in relation to Vendor shall be deemed
        to have occurred upon occurrence of any of the following:
      </p>

      <p>
        (i) Vendor has ceased to carry on or threatens to cease the Business; or
      </p>

      <p>
        (ii) Vendor has passed an effective resolution or a binding order has
        been made for its winding up except under a scheme of amalgamation; or
      </p>

      <p>
        (iii) Vendor has become insolvent or has entered into liquidation
        (unless such liquidation is for the purposes of a fully solvent
        reorganization); or
      </p>

      <p>
        (iv) Vendor has entered into, or taken steps to enter into,
        administration, administrative receivership, receivership, a voluntary
        arrangement, a scheme of arrangement with creditors, any analogous or
        similar procedure in any jurisdiction or any other form of procedure
        relating to insolvency, reorganization or dissolution in any
        jurisdiction, or a petition is presented or other step is taken by any
        person with a view to any of those things.
      </p>

      <h2>14. CONSEQUENCES OF TERMINATION</h2>

      <p>
        14.1 Upon expiry or termination of this Agreement all Confidential
        Information and any other materials which may have been provided by one
        Party to the other shall be forthwith returned and the returning Party
        shall certify such return and all copies thereof or any other material
        or information which cannot be returned, shall be destroyed completely;
      </p>

      <p>
        14.2 Termination of this Agreement shall not relieve any Party of any of
        its obligations or liabilities and affect the rights and remedies of a
        Party, which have accrued prior to the date of termination.
      </p>

      <p>
        14.3 The provisions of this Agreement contained in Sections 9
        (Intellectual Property), 10 (Confidentiality), 11 (Indemnification), 12
        (Representations and Warranties), 14 (Consequences of Termination), 15
        (Governing Law) and 16 (Dispute Resolution), 17.2 (Notices) shall
        survive the expiry or early termination of this Agreement.
      </p>

      <p>
        14.4 Termination of this Agreement shall not affect any obligations or
        duties of the Vendor and Service Provider towards the End Customer which
        obligations or duties accrued before the termination of this Agreement.
      </p>

      <h2>15. GOVERNING LAW</h2>

      <p>
        15.1 This Agreement shall be governed by the laws of India without
        giving effect to its principles of conflict of laws. Subject to the
        provisions of Section 16 (Dispute Resolution); the courts at Delhi shall
        have the exclusive jurisdiction in respect of any matter or dispute
        under or connected with this Agreement, each of the parties hereby
        irrevocably consents to the jurisdiction of such courts (and of the
        appropriate appellate courts therefrom) in any such suit, action or
        proceeding and irrevocably waives, to the fullest extent permitted by
        law, any objection that it may now or hereafter have to the laying of
        the venue of any such suit, action or proceeding in any such court or
        that any such suit, action or proceeding brought in any such court has
        been brought in an inconvenient forum. Process in any such suit, action
        or proceeding may be served on the Vendor anywhere in the world, whether
        within or without the jurisdiction of any such court including on the
        designated electronic mail address.
      </p>

      <p>
        15.2 You and Company shall not accept this Agreement and use the
        Platform if You and Company does not wish to submit to the aforesaid
        applicable laws and jurisdiction.
      </p>

      <h2>16. DISPUTE RESOLUTION</h2>

      <p>
        16.1 Any dispute which arises between the Parties shall be attempted to
        be resolved by good faith discussions between the Parties.
      </p>

      <p>
        16.2 Where the Parties are unable to resolve such disputes by good faith
        discussions within a period of thirty (30) business days from the date
        of a written notice by either Party notifying existence of such dispute,
        either Party shall be free to refer the dispute to arbitration in
        accordance with this Section. This Agreement and the rights and
        obligations of the Parties shall remain in full force and effect pending
        the award in such arbitration proceeding.
      </p>

      <p>
        16.3 The arbitration shall be governed by the Arbitration and
        Conciliation Act, 1996 (as applicable in India) for the time being in
        force, and/or any statutory modification or re-enactment thereof.
      </p>

      <p>
        16.4 The place and seat of arbitration shall be Delhi and the language
        of the arbitration shall be English.
      </p>

      <p>
        16.5 The arbitration shall be conducted by one arbitrator jointly
        appointed by the Parties. In case the Parties fail to appoint their
        respective arbitrators within thirty (30) days from the submission of
        dispute for settlement through arbitration in accordance with Section
        16.2 above, the sole arbitrator shall be appointed in accordance with
        the Indian Arbitration and Conciliation Act, 1996 (as amended upto date)
        by the appropriate court of law.
      </p>

      <p>
        16.6 The award rendered shall be in writing and shall set out the facts
        of the dispute and the reasons for the arbitrator’s decision. The award
        shall apportion the costs of the arbitration as the arbitrator deems
        fair.
      </p>

      <p>
        16.7 Notwithstanding anything contained in this Agreement, both Parties
        agree and acknowledges that the covenants and obligations with respect
        to the matters covered by this Agreement and set forth herein relate to
        special, unique and extraordinary matters, and that a violation of any
        of the terms of such covenants and obligations will cause irreparable
        loss and injury to the aggrieved Party. Therefore notwithstanding the
        provisions of this Agreement, either Party shall be entitled to approach
        any appropriate forums for obtaining an injunction, restraining order or
        such other equitable relief as a court of competent jurisdiction may
        deem necessary or appropriate.
      </p>

      <h2>17. GENERAL CLAUSES</h2>

      <p>
        <strong>17.1 Independent contractors</strong>

        <p>
          The relationship between Parties is on principal-to-principal basis.
          Nothing in this Agreement shall be deemed to constitute either Party a
          partner, joint venture agent or legal representative of the other
          Party, or to create any fiduciary, employer-employee relationship
          between the Parties.
        </p>
      </p>

      <p>
        <strong>17.2 Notices and Correspondences</strong>
        <p>
          Notices: Any notice, consent or waiver (including notice for
          Arbitration) required or permitted hereunder shall be effective only
          if it is in writing and shall be deemed received by the Party to which
          it is sent (i) upon delivery when delivered by hand, (ii) three (3)
          days after being sent, if sent with all sending expenses prepaid, by
          an express courier with a reliable system for tracking delivery, (iii)
          when transmitted, if sent by confirmed facsimile, or (iv) five (5)
          days (if Vendor is in India) or fourteen (14) days (if Vendor is
          outside of India) after the date sent, if sent by certified or
          registered mail, postage prepaid, return receipt requested, addressed
          as follows:
        </p>
        If to the Vendor: If to the Service Provider:
        <p>
          [At the address provided by You] Address: ………………… Tel: …………… Mail:
          ……………. Attention: Mr. ………………….. [Service Provider may change the
          aforesaid address by posting the same on the Platform]
        </p>
        <strong>General communications through electronic mode:</strong>
        <p>
          When the Vendor uses the Platform or send emails or other data,
          information or communication to Service Provider, Vendor agrees and
          understands that Vendor is communicating with Service Provider through
          electronic records and Vendor consents to receive communications via
          electronic records from Service Provider periodically and as and when
          required. Service Provider will communicate with Vendor by email at
          the designated electronic mail address provided by the Vendor at the
          time of registration.
        </p>
      </p>
      <p>
        <strong>17.3 Assignment and Sub-Contracting: </strong>
        Vendor shall not assign any of its rights, obligations or
        responsibilities under this Agreement without the prior written consent
        of Service Provider and in absence of such consent any such assignment
        shall be null and void. All terms and conditions of this Agreement shall
        be binding upon and shall inure to the benefit of the parties hereto and
        their successors and authorized assignees. Vendor understands,
        acknowledges and agrees that Service Provider may sub-contract one or
        more of the Service Provider Business to any third party including
        Affiliates.
      </p>

      <p>
        <strong>17.4 Press Releases / Public Statement:</strong>
        Unless required by law, the Vendor will not make any public announcement
        or issue any press release concerning the transactions contemplated by
        this Agreement without the prior consent of the Service Provider.
      </p>
      <p>
        <strong>
          17.5 Amendment and evolution of Commercial Terms on periodic basis: 
        </strong>
        Service Provider may amend this Agreement, Commercial Terms and Platform
        Policies at any time by posting a revised version on the Platform. All
        updates and amendments may be notified to Vendor on designated
        electronic mail address. Vendor is advised to regularly check for any
        amendments or updates to the terms and conditions contained in this
        Agreement, Commercial Terms and Platform Policies. It is strongly
        advised that Commercial Terms be checked on daily basis as these evolve
        on regular basis based on certain criteria. Vendor’s using Platform,
        Platform Services or Service Provider Business after Service Provider’s
        amendment to this Agreement, Commercial Terms and Platform Policies
        shall be deemed to be Vendor’s unconditional and absolute acceptance of
        such amendments (effective from the date such amendments were made by
        the Service Provider). If Vendor does not agree to the change or
        amendments, Vendor can cease using the Service Provider Business (except
        for those Products which have been bought by the End Customers) and may
        terminate this Agreement as provided in Section 13.2.
      </p>

      <p>
        <strong>17.6 Severability: </strong>
        It is the intent of the Parties that in case any one or more of the
        provisions contained in this Agreement shall be held to be invalid or
        unenforceable in any respect, such provision shall be modified to the
        extent necessary to render it, as modified, valid and enforceable under
        applicable laws and such invalidity or unenforceability shall not affect
        the other provisions of this Agreement.
      </p>

      <p>
        <strong>17.7 Waiver: </strong>
        Except as expressly provided in this Agreement, no waiver of any
        provision of this Agreement shall be effective unless set forth in a
        written instrument signed by the Party waiving such provision. No
        failure or delay by a Party in exercising any right, power or remedy
        under this Agreement shall operate as a waiver thereof, nor shall any
        single or partial exercise of the same preclude any further exercise
        thereof or the exercise of any other right, power or remedy. Without
        limiting the foregoing, no waiver by a Party of any breach by any other
        Party of any provision hereof shall be deemed to be a waiver of any
        preceding or subsequent breach of that or any other provision hereof.
      </p>

      <p>
        <strong>17.8 Further Assurance: </strong>
        Each Party shall co-operate with the other Party and execute and deliver
        to the other Party such instruments and documents and take such other
        actions as may be reasonably requested from time to time in order to
        carry out, evidence and confirm their rights hereunder and the intended
        purpose of this Agreement and to ensure the complete and prompt
        fulfillment, observance and performance of the provisions of this
        Agreement and generally that full effect is given to the provisions of
        this Agreement.
      </p>

      <p>
        <strong>17.9 Covenants Reasonable: </strong>
        The Parties agree that, having regard to all the circumstances, the
        covenants contained herein are reasonable and necessary for the
        protection of the Parties. If any such covenant is held to be void as
        going beyond what is reasonable in all the circumstances but would be
        valid if amended as to scope or duration or both, the covenant will
        apply with such minimum modifications regarding its scope and duration
        as may be necessary to make it valid and effective.
      </p>

      <p>
        <strong>17.10 Independent Rights: </strong>
        Each of the rights of the Parties hereto under this Agreement are
        independent, cumulative and without prejudice to all other rights
        available to them, and the exercise or non-exercise of any such right
        shall not prejudice or constitute a waiver of any other right of the
        Party, whether under this Agreement or otherwise.
      </p>
      <p>
        <strong>17.11 Counsel and management participation: </strong>
        You and Vendor acknowledge and confirm that you attorneys and management
        representatives have read, reviewed and approved this Agreement and that
        You and Vendor have had the benefit of its independent legal counsel’s
        advice with respect to the terms and provisions hereof and its rights
        and obligations hereunder.
      </p>

      <h2>18.	GRIEVANCE OFFICER</h2>

      <p>
      In accordance with Information Technology Act, 2000 and the rules made thereunder, the name and contact details of the Grievance Officer currently is ……………….. with address at ………………………………….. with email ID: grievance@.................... Any change shall be communicated on the Platform. Service of notice for Dispute Resolution and for purposes other than those which are required under Information Technology Act, 2000 to be given only to the Grievance Officer shall not be valid.
      </p>

      {/* <p>
        18.2 Hexbit reserves the right at any time, and from time to time, to
        modify or discontinue, the Services (or any part thereof) with or
        without notice (unless otherwise required by applicable law).
      </p>

      <p>
        18.3 Hexbit shall not be liable to you or to any third party for any
        modification, price change, suspension or discontinuance of the Service.
      </p>

      <h2>19. Third Party Services, Experts, And Experts Marketplace</h2>

      <p>
        19.1 Hexbit may from time to time recommend, provide you with access to,
        or enable third party software, applications (“Apps”), products,
        services or website links (collectively, “Third Party Services”) for
        your consideration or use, including via the Hexbit App Store, or
        Experts Marketplace. Such Third Party Services are made available only
        as a convenience, and your purchase, access or use of any such Third
        Party Services is solely between you and the applicable third party
        services provider (“Third Party Provider”). In addition to these Terms
        of Service, you also agree to be bound by the additional
        service-specific terms applicable to services you purchase from, or that
        are provided by, Third Party Providers.
      </p>

      <p>
        19.2 We do not provide any warranties or make representations to you
        with respect to Third Party Services. You acknowledge that Hexbit has no
        control over Third Party Services and shall not be responsible or liable
        to you or anyone else for such Third Party Services. The availability of
        Third Party Services on Hexbit’s websites, including the Hexbit App
        Store, or the integration or enabling of such Third Party Services with
        the Services does not constitute or imply an endorsement, authorization,
        sponsorship, or affiliation by or with Hexbit. Hexbit does not guarantee
        the availability of Third Party Services and you acknowledge that Hexbit
        may disable access to any Third Party Services at any time in its sole
        discretion and without notice to you. Hexbit is not responsible or
        liable to anyone for discontinuation or suspension of access to, or
        disablement of, any Third Party Service. Hexbit strongly recommends that
        you seek specialist advice before using or relying on Third Party
        Services, to ensure they will meet your needs. In particular, tax
        calculators should be used for reference only and not as a substitute
        for independent tax advice, when assessing the correct tax rates you
        should charge to your customers.
      </p>

      <p>
        19.3 If you install or enable a Third Party Service for use with the
        Services, you grant us permission to allow the applicable Third Party
        Provider to access your data and other Materials and to take any other
        actions as required for the interoperation of the Third Party Service
        with the Services, and any exchange of data or other Materials or other
        interaction between you and the Third Party Provider is solely between
        you and such Third Party Provider. Hexbit is not responsible for any
        disclosure, modification or deletion of your data or other Materials, or
        for any corresponding losses or damages you may suffer, as a result of
        access by a Third Party Service or a Third Party Provider to your data
        or other Materials.
      </p>

      <p>
        19.4 The relationship between you and any Third Party Provider is
        strictly between you and such Third Party Provider, and Hexbit is not
        obligated to intervene in any dispute arising between you and a Third
        Party Provider.
      </p>

      <p>
        19.5 Under no circumstances shall Hexbit be liable for any direct,
        indirect, incidental, special, consequential, punitive, extraordinary,
        exemplary or other damages whatsoever, that result from any Third Party
        Services or your contractual relationship with any Third Party Provider,
        including any Expert. These limitations shall apply even if Hexbit has
        been advised of the possibility of such damages. The foregoing
        limitations shall apply to the fullest extent permitted by applicable
        law.
      </p>

      <p>
        19.6 You agree to indemnify and hold us and (as applicable) our parent,
        subsidiaries, affiliates, Hexbit partners, officers, directors, agents,
        employees, and suppliers harmless from any claim or demand, including
        reasonable attorneys’ fees, arising out of your use of a Third Party
        Service or your relationship with a Third Party Provider.
      </p>

      <h2>20. Feedback And Reviews</h2>

      <p>
        Hexbit welcomes any ideas and/or suggestions regarding improvements or
        additions to the Services.
      </p>

      <h2>21. Rights Of Third Parties</h2>

      <p>
        Save for Hexbit and its affiliates, Hexbit Users or anyone accessing
        Hexbit Services pursuant to these Terms of Service, unless otherwise
        provided in these Terms of Service, no person or entity who is not a
        party to these Terms of Service shall have any right to enforce any term
        of these Terms of Service, regardless of whether such person or entity
        has been identified by name, as a member of a class or as answering a
        particular description. For the avoidance of doubt, this shall not
        affect the rights of any permitted assignee or transferee of these
        Terms.
      </p>

      <h2>22. Privacy & Data Protection</h2>

      <p>
        Hexbit is firmly committed to protecting the privacy of your personal
        information and the personal information of your customers. By using the
        Service, you acknowledge and agree that Hexbit’s collection, usage and
        disclosure of this personal information is governed by our Privacy
        Policy.
      </p>

      <h2>23. Miscellaneous</h2>

      <p>
        23.1 Use of Third Parties for Payment Processing. Hexbit may use a
        third-party service provider to manage payment processing provided that
        such service provider is not permitted to store, retain, or use
        Customer’s payment account information except to process Customer’s
        payment information for Hexbit. Customer must notify Hexbit of any
        change in Customer’s payment account information, either by updating
        Customer’s Account and by e-mailing Hexbit at support@Hexbit.ai
      </p>

      <p>
        23.2 Assignment. Neither party may assign any of its rights or
        obligations hereunder, whether by operation of law or otherwise, without
        the other party’s prior written consent (not to be unreasonably
        withheld); provided, however, either party may assign this Agreement in
        its entirety, without the other party’s consent to its Affiliate or in
        connection with a merger, acquisition, corporate reorganization, or sale
        of all or substantially all of its assets. Any attempted assignment in
        violation of this section will be null and void.
      </p>

      <p>
        23.3 Waiver and Severability. The failure of Hexbit to exercise or
        enforce any right or provision of the Terms of Service shall not
        constitute a waiver of such right or provision. If any provision of the
        Terms of Service, including all terms and conditions and other documents
        it incorporates by reference, is held by a court of competent
        jurisdiction to be contrary to law, such provision shall be changed and
        interpreted so as to best accomplish the objectives of the original
        provision to the fullest extent allowed by law, and the remaining
        provision of the Terms of Service shall remain in full force and effect.
      </p>

      <p>
        23.4 Entire Agreement. This Agreement, together with any Supplement
        terms, constitutes the entire agreement and supersedes any and all prior
        agreements or communications between Customer and Hexbit regarding the
        subject matter hereof. If any provision in this Agreement is held by a
        court of competent jurisdiction to be unenforceable, such provision will
        be modified by the court and interpreted so as to best accomplish the
        original.
      </p>

      <p>
        23.5 Publicity Rights. Hexbit may identify Customer as a Hexbit customer
        in its promotional materials. Customer may request that Hexbit stop
        doing so by submitting an email to support@Hexbit.ai at any time. Please
        note that it may take us up to thirty (30) days to process a request.
      </p>

      <p>
        23.6 Relationship of the Parties. The parties are independent
        contractors. This Agreement does not create a partnership, franchise,
        joint venture, agency, fiduciary or employment relationship among the
        parties.
      </p>

      <p>
        23.7 Survival. Sections 7.b (Use Restrictions), 9 (Intellectual
        Property), 13 (Fees and Payment), 14 (Term, Termination and Suspension),
        15 (Confidentiality), 16 (Warranty Disclaimer), 17 (Limitation of
        Liability), 18 (Indemnification), 24.d (Entire Agreement), 24.g
        (Survival), 24.h. (Notices), 24.k (Governing Law) and 24.l (Dispute
        Resolution) and 25 (Definitions) will survive any termination of the
        Agreement. Termination of this Agreement will not limit either party’s
        liability for obligations accrued as of or prior to such termination or
        for any breach of this Agreement.
      </p>

      <p>
        23.8 Notices. All notices to be provided by one party to the other under
        this Agreement may be delivered in writing to the mailing address
        provided in the agreement. The address for a notice to Hexbit is: Hexbit
        Unit No. 138, 1st Floor, Satguru Nanik Industrial Estate, Western
        Express Highway, Goregaon East, Mumbai-400063, Mahasrahtra, India with a
        copy to support@Hexbit.ai by electronic mail. All notices will be deemed
        to have been given immediately upon delivery by electronic mail, or if
        otherwise delivered upon receipt or, if earlier, five (5) business days
        after being deposited in the mail or with a courier as permitted above.
      </p>

      <p>
        23.9 Anti-Corruption. Neither party has received or been offered any
        illegal or improper bribe, kickback, payment, gift, or thing of value
        from an employee or agent of the other party in connection with this
        Agreement. Reasonable gifts and entertainment provided in the ordinary
        course of business do not violate the above restriction. If Customer
        learns of any violation of the above restriction, Customer will use
        reasonable efforts to promptly notify Hexbit at support@Hexbit.ai
      </p>

      <p>
        23.10 Force Majeure. Neither party will be liable to the other for any
        delay or failure to perform any obligation under this Agreement if the
        delay or failure results from any cause beyond such party’s reasonable
        control, including but not limited to, acts of God, acts of government,
        acts of terror or civil unrest, Internet failures, or acts undertaken by
        third parties not under the performing party’s control, including,
        without limitation, denial of service attacks (“Force Majeure Event”).
        In the event that a Force Majeure Event continues for a period of thirty
        (30) consecutive days, the other party may terminate this Agreement on
        written notice to the non-performing party. If Hexbit is the party
        experiencing the Force Majeure Event and as a result thereof is unable
        to provide the Services, Software or Mobile Apps for the period noted
        herein, and Customer terminates this Agreement, then Hexbit will provide
        Customer a refund of fees paid by Customer pro-rated as of the date the
        Force Majeure Event commenced.
      </p>

      <p>
        23.11 Governing Law. This Agreement is governed by the laws of India.
        The parties hereby submit to the exclusive jurisdiction of Mumbai, for
        any claims or dispute relating to this Agreement.
      </p>

      <p>
        23.12 Dispute Resolution. Any dispute, claim or controversy arising out
        of or relating to this Agreement or the breach, termination,
        enforcement, interpretation, or validity thereof, including the
        determination of the scope or applicability of this Agreement to
        arbitrate, will be determined by arbitration in Mumbai, India. Judgment
        on the Award may be entered in any court having jurisdiction. This
        section will not preclude parties from seeking provisional remedies in
        aid of arbitration from a court of appropriate jurisdiction.
      </p>

      <p>
        23.13 Representation. The user utilizing any service as an employee,
        agent or contractor of a company, Partnership or similar entity,
        represents and warrants that he / she has the authority to sign for and
        bind such entity in order to accept the terms of this agreement. The
        Rights granted under this agreement are expressly conditioned upon
        acceptance by such authorized personnel.
      </p>

      <p>
        23.14 Modifications to this Agreement. From time to time, Hexbit may
        modify this Agreement. Changes to this Agreement will not apply
        retrospectively and will become effective no sooner than 14 days after
        they are posted. Hexbit will use reasonable efforts to notify Customer
        of the changes through communications via Customer’s Account, email or
        other means.{" "}
      </p>

      <p>
        23.15 “Effective Date” of this Agreement is the date which is the
        Customer’s initial access to any Service through online registration or
        order process. This Agreement will govern Customer’s initial purchase on
        the Effective Date as well as any future purchases made by Customer that
        reference this Agreement.
      </p>

      <p>
        23.16 Acceptance: By accepting this agreement or accessing this using
        this service, you are agreeing to the terms and conditions of this
        agreement.
      </p>

      <h2>24. Definitions</h2>

      <p>
        “Account” means any accounts or instances created by or on behalf of
        Customer for access to and use of any of the Services.
      </p>

      <p>
        “Affiliate" or "Subsidiary" means, with respect to a party to this
        Agreement, any entity that directly or indirectly controls, is
        controlled by, or is under common control with such party, where
        “control” means the possession, directly or indirectly, of the power to
        direct, or cause the direction of the management and policies of such
        entity, whether through the ownership of voting securities, by contract,
        or otherwise.
      </p>

      <p>
        “Confidential Information” shall include, but shall not be limited to,
        any and all information associated with a party’s business and not
        publicly known, including specific business information, technical
        processes and formulas, software, customer lists, prospective customer
        lists, names, addresses and other information regarding customers and
        prospective customers, product designs, sales, costs (including any
        relevant processing fees), price lists, and other unpublished financial
        information, business plans and marketing data, and any other
        confidential and proprietary information, whether or not marked as
        confidential or proprietary. Hexbit’s Confidential Information includes
        all information that you receive relating to us, or to the Services,
        that is not known to the general public including information related to
        our security program and practices. Confidential Information does not
        include any information that:{" "}
      </p>

      <p>
        (a) was publicly known and made generally available in the public domain
        prior to the time of disclosure by the disclosing party;{" "}
      </p>

      <p>
        (b) becomes publicly known and made generally available through no
        action or inaction of the receiving party;{" "}
      </p>

      <p>
        (c) is already in the possession of the receiving party at the time of
        disclosure by the disclosing party;{" "}
      </p>

      <p>
        (d) is obtained by the receiving party from a third party without a
        breach of such third party’s obligations of confidentiality;{" "}
      </p>

      <p>
        (e) is independently developed by the receiving party without use of or
        reference to the disclosing party’s Confidential Information.
      </p>

      <p>
        “Customer Data” means, all electronic data, text, messages or other
        materials, including, without limitation, Personal Data of Users and End
        Users, submitted to the Services by Customer or its Users through
        Customer’s Account in connection with Customer’ use of the Services.
      </p>

      <p>
        “Documentation” means, the then-current, generally available user
        documentation provided by Hexbit detailing the functionalities of the
        Software and the Services.
      </p>

      <p>
        “End User” means, any person or entity other than Customer authorized by
        it for using the Services.
      </p>

      <p>
        “Order Form” means, (i) any service order referencing this Agreement and
        executed by Customer and Hexbit, or (ii) any online ordering document or
        process completed by Customer, including any online registration through
        a Website, each of which detail, the Services subscribed to and
        corresponding Service Plans, Fees payable to Hexbit, the applicable
        Subscription Term, and any relevant additional terms and conditions.
      </p>

      <p>
        “Hexbit Technology” means, (i) the Services, Software, Mobile Apps,
        Documentation, Hexbit’ APIs, Hexbit’ website(s) and any content
        published on the Hexbit’ websites, (ii) any training materials, support
        materials, templates, tools, methodologies or know-how, (iii) Hexbit’
        Confidential Information and (iv) any modifications or derivative works
        of the foregoing.
      </p>

      <p>
        “Mobile App” means, the Hexbit-branded Software applications provided by
        Hexbit to enable access and use of the Services through mobile or other
        handheld devices (such as apps on iOS or Android devices).
      </p>

      <p>
        “Personal Data” means, data relating to an individual who is or can be
        identified either from the data or from the data in conjunction with
        other information that is in, or is likely to come into, the possession
        of the data controller (as defined under applicable data protection
        laws).
      </p>

      <p>
        “Privacy Policy” means, Hexbit’ privacy policy currently at
        Hexbit.ai/privacy-policy as updated from time to time
      </p>

      <p>
        “Services” means, the Hexbit software-based service offerings identified
        in the agreement orSupplement terms, and any Updates, including any
        Software, API or Documentation made available by Hexbit with such
        offering, but excludes any applications or APIs separately provided by
        third parties.
      </p>

      <p>
        “Service Plans” means, the pricing plans and other packaged offering
        limitations for and the applicable Services for which Customer
        subscribes with respect to any User.
      </p>

      <p>
        “Software” means the generally available software provided by Hexbit in
        connection with Customer’s use of the Services, and includes Mobile
        Apps, but excludes any applications or APIs that are provided by third
        parties.
      </p>

      <p>
        “Subscription Term” means, the period stated in the “Order form” during
        which Customer subscribes to the Services.
      </p>

      <p>
        “Supplemental Terms” means, the Services specific terms in addition to
        this agreement.
      </p>
      <p>
        “Update” means, the generally available updates, upgrades, hot fixes,
        patches, workarounds to the Software or Service provided by Hexbit to
        all subscribing customers, but excludes separately priced new products
        or modules.
      </p>

      <p>
        “User” or “Agent” means, any individual who is authorized by Customer to
        use the Services, including an Account administrator, employees,
        consultants, contractors, and agents of Customer or its Affiliates, and
        third parties with which Customer or its Affiliates transact business.
        </p>*/}
    </div>
  );
};

export default TermsContent; 
